version: '3.8'

services:
  jellyfin-manager:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        - ARCH=${ARCH:-amd64}
    image: jellyfin-manager:${TAG:-latest}
    container_name: jellyfin-manager
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      # Database URL is set in the Dockerfile to use SQLite
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s