version: '3.8'

services:
  jellyfin-manager:
    build:
      context: .
      dockerfile: ${DOCKERFILE:-Dockerfile}
      args:
        - ARCH=${ARCH:-amd64}
    image: jellyfin-manager:${TAG:-latest}
    container_name: jellyfin-manager
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/jellyfin-manager
    volumes:
      - ./config:/app/config
      - ./data:/app/data
    depends_on:
      - db
    networks:
      - jellyfin-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5000/api/system/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  db:
    image: postgres:15-alpine
    container_name: jellyfin-manager-db
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jellyfin-manager
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - jellyfin-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  jellyfin-network:
    driver: bridge

volumes:
  postgres-data: